// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: example.proto

package exampleconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	example "github.com/lcmaguire/protoc-gen-go-goo/example"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ExampleServiceName is the fully-qualified name of the ExampleService service.
	ExampleServiceName = "tutorial.ExampleService"
	// ExtraExampleServiceName is the fully-qualified name of the ExtraExampleService service.
	ExtraExampleServiceName = "tutorial.ExtraExampleService"
)

// ExampleServiceClient is a client for the tutorial.ExampleService service.
type ExampleServiceClient interface {
	GetExample(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error)
	CreateExample(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error)
	ListExamples(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error)
	DeleteExamples(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error)
}

// NewExampleServiceClient constructs a client for the tutorial.ExampleService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExampleServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ExampleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &exampleServiceClient{
		getExample: connect_go.NewClient[example.SearchRequest, example.SearchResponse](
			httpClient,
			baseURL+"/tutorial.ExampleService/GetExample",
			opts...,
		),
		createExample: connect_go.NewClient[example.SearchRequest, example.SearchResponse](
			httpClient,
			baseURL+"/tutorial.ExampleService/CreateExample",
			opts...,
		),
		listExamples: connect_go.NewClient[example.SearchRequest, example.SearchResponse](
			httpClient,
			baseURL+"/tutorial.ExampleService/ListExamples",
			opts...,
		),
		deleteExamples: connect_go.NewClient[example.SearchRequest, example.SearchResponse](
			httpClient,
			baseURL+"/tutorial.ExampleService/DeleteExamples",
			opts...,
		),
	}
}

// exampleServiceClient implements ExampleServiceClient.
type exampleServiceClient struct {
	getExample     *connect_go.Client[example.SearchRequest, example.SearchResponse]
	createExample  *connect_go.Client[example.SearchRequest, example.SearchResponse]
	listExamples   *connect_go.Client[example.SearchRequest, example.SearchResponse]
	deleteExamples *connect_go.Client[example.SearchRequest, example.SearchResponse]
}

// GetExample calls tutorial.ExampleService.GetExample.
func (c *exampleServiceClient) GetExample(ctx context.Context, req *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error) {
	return c.getExample.CallUnary(ctx, req)
}

// CreateExample calls tutorial.ExampleService.CreateExample.
func (c *exampleServiceClient) CreateExample(ctx context.Context, req *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error) {
	return c.createExample.CallUnary(ctx, req)
}

// ListExamples calls tutorial.ExampleService.ListExamples.
func (c *exampleServiceClient) ListExamples(ctx context.Context, req *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error) {
	return c.listExamples.CallUnary(ctx, req)
}

// DeleteExamples calls tutorial.ExampleService.DeleteExamples.
func (c *exampleServiceClient) DeleteExamples(ctx context.Context, req *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error) {
	return c.deleteExamples.CallUnary(ctx, req)
}

// ExampleServiceHandler is an implementation of the tutorial.ExampleService service.
type ExampleServiceHandler interface {
	GetExample(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error)
	CreateExample(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error)
	ListExamples(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error)
	DeleteExamples(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error)
}

// NewExampleServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExampleServiceHandler(svc ExampleServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/tutorial.ExampleService/GetExample", connect_go.NewUnaryHandler(
		"/tutorial.ExampleService/GetExample",
		svc.GetExample,
		opts...,
	))
	mux.Handle("/tutorial.ExampleService/CreateExample", connect_go.NewUnaryHandler(
		"/tutorial.ExampleService/CreateExample",
		svc.CreateExample,
		opts...,
	))
	mux.Handle("/tutorial.ExampleService/ListExamples", connect_go.NewUnaryHandler(
		"/tutorial.ExampleService/ListExamples",
		svc.ListExamples,
		opts...,
	))
	mux.Handle("/tutorial.ExampleService/DeleteExamples", connect_go.NewUnaryHandler(
		"/tutorial.ExampleService/DeleteExamples",
		svc.DeleteExamples,
		opts...,
	))
	return "/tutorial.ExampleService/", mux
}

// UnimplementedExampleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExampleServiceHandler struct{}

func (UnimplementedExampleServiceHandler) GetExample(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("tutorial.ExampleService.GetExample is not implemented"))
}

func (UnimplementedExampleServiceHandler) CreateExample(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("tutorial.ExampleService.CreateExample is not implemented"))
}

func (UnimplementedExampleServiceHandler) ListExamples(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("tutorial.ExampleService.ListExamples is not implemented"))
}

func (UnimplementedExampleServiceHandler) DeleteExamples(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("tutorial.ExampleService.DeleteExamples is not implemented"))
}

// ExtraExampleServiceClient is a client for the tutorial.ExtraExampleService service.
type ExtraExampleServiceClient interface {
	GetExample(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error)
	DeleteExamples(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[emptypb.Empty], error)
}

// NewExtraExampleServiceClient constructs a client for the tutorial.ExtraExampleService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExtraExampleServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ExtraExampleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &extraExampleServiceClient{
		getExample: connect_go.NewClient[example.SearchRequest, example.SearchResponse](
			httpClient,
			baseURL+"/tutorial.ExtraExampleService/GetExample",
			opts...,
		),
		deleteExamples: connect_go.NewClient[example.SearchRequest, emptypb.Empty](
			httpClient,
			baseURL+"/tutorial.ExtraExampleService/DeleteExamples",
			opts...,
		),
	}
}

// extraExampleServiceClient implements ExtraExampleServiceClient.
type extraExampleServiceClient struct {
	getExample     *connect_go.Client[example.SearchRequest, example.SearchResponse]
	deleteExamples *connect_go.Client[example.SearchRequest, emptypb.Empty]
}

// GetExample calls tutorial.ExtraExampleService.GetExample.
func (c *extraExampleServiceClient) GetExample(ctx context.Context, req *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error) {
	return c.getExample.CallUnary(ctx, req)
}

// DeleteExamples calls tutorial.ExtraExampleService.DeleteExamples.
func (c *extraExampleServiceClient) DeleteExamples(ctx context.Context, req *connect_go.Request[example.SearchRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return c.deleteExamples.CallUnary(ctx, req)
}

// ExtraExampleServiceHandler is an implementation of the tutorial.ExtraExampleService service.
type ExtraExampleServiceHandler interface {
	GetExample(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error)
	DeleteExamples(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[emptypb.Empty], error)
}

// NewExtraExampleServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExtraExampleServiceHandler(svc ExtraExampleServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/tutorial.ExtraExampleService/GetExample", connect_go.NewUnaryHandler(
		"/tutorial.ExtraExampleService/GetExample",
		svc.GetExample,
		opts...,
	))
	mux.Handle("/tutorial.ExtraExampleService/DeleteExamples", connect_go.NewUnaryHandler(
		"/tutorial.ExtraExampleService/DeleteExamples",
		svc.DeleteExamples,
		opts...,
	))
	return "/tutorial.ExtraExampleService/", mux
}

// UnimplementedExtraExampleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExtraExampleServiceHandler struct{}

func (UnimplementedExtraExampleServiceHandler) GetExample(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[example.SearchResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("tutorial.ExtraExampleService.GetExample is not implemented"))
}

func (UnimplementedExtraExampleServiceHandler) DeleteExamples(context.Context, *connect_go.Request[example.SearchRequest]) (*connect_go.Response[emptypb.Empty], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("tutorial.ExtraExampleService.DeleteExamples is not implemented"))
}
